spring:
  application:
    name: Config-Prod
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
